# Generated by Django 3.2.4 on 2021-06-23 19:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('tagline', models.CharField(max_length=2320)),
                ('description', ckeditor.fields.RichTextField(default=False)),
                ('address', models.CharField(max_length=2320)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=128, region=None)),
                ('url', models.CharField(max_length=2220)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('published', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('plan', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapp.businesscategory')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.BooleanField(default=False)),
                ('call_list', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Must be international format eg: +1 555 555 55555', max_length=128, region=None)),
                ('note', models.TextField(help_text='Notes')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField(default=False)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('featured', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapp.author')),
                ('categories', models.ManyToManyField(to='theapp.Category')),
                ('next_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='theapp.post')),
                ('previous_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='theapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapp.businesslisting')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=320)),
                ('answer', models.CharField(max_length=1520)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapp.businesslisting')),
            ],
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theapp.businesslocation'),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.CharField(max_length=220)),
                ('monday_closed', models.CharField(max_length=220)),
                ('tuesday_open', models.CharField(max_length=220)),
                ('tuesday_closed', models.CharField(max_length=220)),
                ('wednesday_open', models.CharField(max_length=220)),
                ('wednesday_closed', models.CharField(max_length=220)),
                ('thursday_open', models.CharField(max_length=220)),
                ('thursday_closed', models.CharField(max_length=220)),
                ('friday_open', models.CharField(max_length=220)),
                ('friday_closed', models.CharField(max_length=220)),
                ('saturday_open', models.CharField(max_length=220)),
                ('saturday_closed', models.CharField(max_length=220)),
                ('sunday_open', models.CharField(max_length=220)),
                ('sunday_closed', models.CharField(max_length=220)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapp.businesslisting')),
            ],
        ),
    ]
