# Generated by Django 3.2.4 on 2021-06-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
