# Generated by Django 3.2.4 on 2021-06-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
