# Generated by Django 3.2.4 on 2021-06-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
