# Generated by Django 3.2.4 on 2021-06-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0006_auto_20210624_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshours',
            old_name='friday_closed',
            new_name='m_f_closed',
        ),
        migrations.RenameField(
            model_name='businesshours',
            old_name='friday_open',
            new_name='m_f_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='monday_closed',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='monday_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='thursday_closed',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='thursday_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='tuesday_closed',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='tuesday_open',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='wednesday_closed',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='wednesday_open',
        ),
    ]
